=== erickvargas10/SOA_XML_XSD/XML-XSD/src/java/Deber/DeberXSD.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
           
    <xs:element name="productos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="identificacion">
                                <xs:complexType mixed="true">
                                    <xs:all>
                                        <xs:element type="xs:string" name="codigo"/>
                                        <xs:element type="xs:int" name="id" minOccurs="0"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="nombre"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

Salami Slice â€“ XSD

<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <!-- Elementos Globales -->
    <xs:element name="productos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="producto" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Elementos Simples -->
    <xs:element name="codigo" type="xs:string"/>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="id" type="xs:int"/>
    
    <!-- Elementos Complejos -->    
    <xs:element name="producto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="identificacion"/>
                <xs:element ref="nombre"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="identificacion">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="codigo"/>
                <xs:element ref="id" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== erickvargas10/SOA_XML_XSD/XML-XSD/src/java/Deber/Deber.xml
<?xml version="1.0" encoding="UTF-8"?>
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="DeberXSD.xsd">
    <producto>
        <identificacion>
            Quedan 30 unidades
            <codigo>VIN456</codigo>
        </identificacion>
        <nombre>VINO</nombre>
    </producto> 
    <producto>
        <identificacion>
            <codigo>ACE987</codigo>
            <id>6353</id>
            No hay stock.
        </identificacion>
        <nombre>ACEITE</nombre>
    </producto>
</productos>
